name: py312
channels:
  - conda-forge
  - defaults
dependencies:
  - conda=24.1.2  
  - python=3.12.3
  - pip=24.0
  - pydantic=2.6.1
  - autopep8=2.0.4
  - pyyaml=6.0.1
  - tqdm=4.66.1
  - lxml=5.1.0
  - colorama=0.4.6
  - urllib3=2.2.0
  - httplib2=0.22.0
  - pyjwt[crypto]=2.8.0
  - pandas=2.2.0
  - numpy=1.26.4
  - requests=2.31.0
  - fastapi=0.109.2
  - uvicorn=0.27.0.post1
  - toolz=0.12.1
  - unsync=1.4.0
  - python-dotenv=1.0.1
  - psycopg2-binary=2.9.9
  - jupyter=1.0.0
  - pytest=8.0.0
  - aiohttp=3.9.1
  - aiofiles=22.1.0
  - faker=23.1.0
  - logging_tree=1.9
  - msgspec=0.18.6
  - flake8=7.0.0
  - python-json-logger=2.0.7
  - pip:
    - aiologger

